server:
  port: 9090
  flyway:
    enabled: false

spring:
  application:
    name: t1-banking
  datasource:
    url: jdbc:postgresql://localhost:5432/account_processing
    username: postgres
    password: Qwe123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-processing
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

ru:
  t1bank:
    kafka:
      topic:
        client_transactions: client_transactions
        client_payments: client_payments

fraud:
  transaction:
    limit:
      count: 10
      period:
        minutes: 1