server:
  port: 9095
  flyway:
    enabled: false

spring:
  application:
    name: t1-banking
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_processing
    username: postgres
    password: Qwe123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: credit-processing
    producer:
      enable: true

  credit:
    limit: 100000.0
  client:
    processing:
      url: http://localhost:9099

ru:
  t1bank:
    kafka:
      topic:
      service_logs: service_logs

metric:
  time-limit-ms: 2000

cache:
  ttl-seconds: 60

security:
  jwt:
    secret: key
    expiration: 3600000